// Generated by CIRCT unknown git version
module Buffer(	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_struct.py:4
  input                                                   clk,
  input  struct packed {logic valid; logic [31:0] data; } master,
  output [31:0]                                           out
);

  reg [31:0] master__data__reg1;	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_struct.py:14
  reg [31:0] master__data__reg2;	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_struct.py:14
  always_ff @(posedge clk) begin	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_struct.py:14
    master__data__reg1 <= master.data;	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_struct.py:14
    master__data__reg2 <= master__data__reg1;	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_struct.py:14
  end // always_ff @(posedge)
  assign out = master.valid ? 32'h0 : master__data__reg2;	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_struct.py:12, :14
endmodule

