// Generated by CIRCT unknown git version
module MUX2(	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_MUX2.py:10
  input         op,
  input  [31:0] a,
                b,
  output [31:0] out
);

  assign out = op ? b : a;	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_MUX2.py:16, :18
endmodule

