// Generated by CIRCT unknown git version
module OrInts(	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_bit_or.py:6
  input  [31:0] a,
                b,
  output [31:0] c
);

  assign c = a | b;	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_bit_or.py:11, :13
endmodule

