// Generated by CIRCT unknown git version
module Signal_concat(	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_signal_concat.py:4
  input  [3:0] a,
               b,
  output [7:0] out
);

  assign out = {a, b};	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_signal_concat.py:9, :11
endmodule

