// Generated by CIRCT unknown git version
module Top(	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_bit_or.py:16
  input  [31:0] a,
                b,
  output [31:0] c
);

  OrInts OrInts (	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_bit_or.py:23
    .a (a),
    .b (b),
    .c (c)
  );	// /Users/shaialexander/pycde_venv/circt/frontends/PyCDE/test/simple_example_for_test/test_bit_or.py:23
endmodule

